image: alpine/edge
secrets:
  - 1b3fe3d9-ee86-4c7e-bd35-d0c87b6e12a9
  - a21aaecc-c71f-44b7-bd5e-360064646011
environment:
  REPO_NAME: rust-wasm-yew-single-page-application
  DOCKER_HUB_USER: aaronkelly
sources:
  - git+ssh://git@git.sr.ht/~aaronkelly/rust-wasm-yew-single-page-application
packages:
  - docker
tasks:
  - setup-docker: |-
      sudo service docker start && \
              sudo addgroup $(id -u -n) docker && \
              ping www.cloudflare.com -c 5
  - build-image: |-
      cd "$REPO_NAME"
      docker build -t "$DOCKER_HUB_USER"/"$REPO_NAME" .
  - push-to-dockerhub: |-
      docker login --username "$DOCKER_HUB_USER" \
        --password $(cat ~/DOCKER_HUB_PASS)
      docker push "$DOCKER_HUB_USER"/"$REPO_NAME"
